# Show the release status (should be FAILED or PENDING)
helm status demo-prometheus -n demo-monitoring

# Show exactly which hooks ran (and which are still pending)
helm get hooks demo-prometheus -n demo-monitoring


kubectl get events -n demo-monitoring --sort-by=.metadata.creationTimestamp

kubectl describe job <hook–job-name> -n demo-monitoring
kubectl logs job/<hook–job-name> -n demo-monitoring

kubectl get clusterrole kube-prometheus-stack-grafana-clusterrole -o yaml

