apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::202523371796:role/gh-eks-deploy
      username: github-monitoring-ci
      groups:
        - system:masters
