apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-kube
  region: us-east-1
  version: "1.30"

vpc:
  id: "vpc-05caa828685e9a611"
  subnets:
    private:
      private-1: { id: "subnet-05cfbfc5a95afa918" }
      private-2: { id: "subnet-05867714d0bfb6ad9" }
      private-3: { id: "subnet-0edfec5db9f78d863" }

  clusterEndpoints:
    publicAccess: true
    privateAccess: false

nodeGroups:
  - name: ng-1
    instanceType: t3a.small
    desiredCapacity: 3
    minSize: 1
    maxSize: 6
    privateNetworking: true
    securityGroups:
      attachIDs:
        - "sg-0123456789abcdef0"  #  replace with your real SG ID



# Remove old one if it exists
sudo rm -f /usr/local/bin/aws-iam-authenticator

# Download the correct version (x86_64 / amd64)
curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.30.0/2024-05-09/bin/linux/amd64/aws-iam-authenticator

# Make it executable
chmod +x aws-iam-authenticator

# Move it to your PATH
sudo mv aws-iam-authenticator /usr/local/bin/

# Verify
aws-iam-authenticator version


curl -L -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.30.0/2024-05-09/bin/linux/amd64/aws-iam-authenticator
chmod +x aws-iam-authenticator
sudo mv aws-iam-authenticator /usr/local/bin/

